name: mu-watch

on:
  schedule:
    - cron: "*/5 * * * *"   # a cada 5 minutos
  workflow_dispatch: {}     # rodar manualmente

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # salvar .state.json no repo (opcional)
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Playwright
        run: |
          npm install
          npx playwright install --with-deps chromium

      - name: Run watcher
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          MU_BASE_URL: https://mudream.online
          MU_CHAR_PATH: /pt/char/
          WATCHLIST_FILE: watchlist.txt
          STATE_FILE: .state.json
        run: node watcher.js

      - name: Commit state
        if: always()
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name "mu-watch-bot"
          git add .state.json || true
          git commit -m "update state [skip ci]" || true
          git push || true
