name: mu-watch

on:
  schedule:
    - cron: "*/45 * * * *"   # a cada 5 min
  workflow_dispatch: {}     # executar manualmente

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # para commitar .state.json
    steps:
      - uses: actions/checkout@v4

      - name: Verify source version
        run: |
          echo "HEAD watcher.js preview (linhas 1..120):"
          sed -n '1,120p' watcher.js || true
          if grep -n 'waitUntil: "networkidle"' watcher.js; then
            echo "ERRO: ainda tem networkidle no watcher.js";
            exit 1;
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Playwright
        run: |
          npm install
          npx playwright install --with-deps chromium

      - name: Run watcher
        timeout-minutes: 5
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          MU_BASE_URL: https://mudream.online
          MU_CHAR_PATH: /pt/char/
          WATCHLIST_FILE: watchlist.txt
          STATE_FILE: .state.json
          GIT_PERSIST: '1'         # pra commitar o state.json
          # FORCE_POST: '1'        # opcional pra forçar envio
        run: |
          node -v
          node watcher.js

      - name: Commit state
        if: always()
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name "mu-watch-bot"
          git add .state.json || true
          git commit -m "update state [skip ci]" || true
          git push || true
